global_args:
  # 调试模式: 设置为 true 时，只会处理一个样本并打印详细的输入输出信息
  debug: true
  # 结果将保存在此根目录下, 按模型名称分子目录
  output_dir: "./results/"

dataset_args:
  # 数据集根目录和名称
  data_path: ./data
  dataset: Instruments
  # 默认索引文件, 可在模型配置中被覆盖
  index_file: ".index_llama-td.json"
  ratio_dataset: 1

test_args:
  # --- 全局测试参数 ---
  test_task: "seqrec" # or "itemsearch", "fusionseqrec"
  test_prompt_ids: "0" # or "0,1,2"
  test_batch_size: 16
  num_beams: 20
  metrics: "hit@1,hit@5,hit@10,ndcg@5,ndcg@10"
  filter_items: false
  use_constrained_generation: false
  max_new_tokens: 4
  print_freq: 100

  # --- 模型列表 ---
  # 在此定义所有需要参加评测的模型
  models:
    - name: "Qwen-VL-Finetune"
      enabled: true
      model_type: "qwen_vl"
      path: "./ckpt/base_model/Qwen2.5-VL-3B-Instruct"
      lora: false
      ckpt_path: "./ckpt/Instruments/Qwen2-VL-2B-Instruct-finetune-seqrec-llama-td-with-id-1/checkpoint-10612"
      # 特定于此模型的索引文件
      index_file: ".index_llama-td.json"